### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fcorowe** [16EAGLE/basemaps#3]
First of all, thanks for this great package. 

I am trying to load the package and I get the error below

```
library(basemaps)
Error: package or namespace load failed for ‘basemaps’:
 object ‘st_set_bbox’ is not exported by 'namespace:stars'
```
 ‘st_set_bbox’ is not being exported by 'namespace:stars'

Any ideas on how to resolve it?

**Comment by 16EAGLE** [comment]
Thank you.

Which version of `stars` is installed on your system? Might it be possible that you have a  `stars` version `< 0.5-0` installed? `st_set_bbox` is exported by `stars` only since version `0.5-0` (see `?stars::st_set_bbox`) which means you need at least `stars 0.5-0` for `basemaps` to work.

Could you try installing the newest `stars` version form CRAN using `install.packages("stars")`, then reinstall `basemaps` and run `library(basemaps)` again?

**Comment by 16EAGLE** [comment]
please reopen if issue persists.

**Comment by fcorowe** [comment]
Sorry - just catching up with this. Yes, that was the problem. I now have 0.5.3 and all works well. Thanks
