### ISSUE TITLE
Maptiler Aquarelle tiles aren't working

### ISSUE THREAD

**Issue by markbidwell** [16EAGLE/basemaps#32]
Hi Jakob - thank you for making Basemaps, it's great!

It seems the [Aquarelle ](https://cloud.maptiler.com/maps/aquarelle/?_gl=1*19lzejh*_ga*ODU3NDY4OTg3LjE3MzE1MzE1NzQ.*_ga_K4SXYBF4HT*MTczMTUzMTU3NC4xLjEuMTczMTUzMjg2MC40LjAuMA..)tiles from Maptiler aren't working. Here's a quick reprex:

> data(ext)
> set_defaults(ext = ext, map_res=1.0, map_service = "maptiler", map_type = "aquarelle", map_token="Insert Your API Key Here")
> map <- basemap()

Loading basemap 'Aquarelle' from map service 'maptiler'...
0 % ~calculating  Error: Tile download failed: HTTP response code said error [0.0.0.10]: The requested URL returned error: 502

However, all of the other Maptiler tiles listed in get_maptypes() seem to work, just not Aquarelle.

If you're able to get this working, would it also be possible to add [Aquarelle Dark](https://cloud.maptiler.com/maps/aquarelle-dark/?_gl=1*1yv73ot*_ga*ODU3NDY4OTg3LjE3MzE1MzE1NzQ.*_ga_K4SXYBF4HT*MTczMTUzMTU3NC4xLjEuMTczMTUzMjgwNi41OC4wLjA.) and [Aquarelle Vivid](https://cloud.maptiler.com/maps/aquarelle-vivid/?_gl=1*aul963*_ga*ODU3NDY4OTg3LjE3MzE1MzE1NzQ.*_ga_K4SXYBF4HT*MTczMTUzMTU3NC4xLjEuMTczMTUzMjgzOS4yNS4wLjA.)?

Thank you, Mark

**Comment by 16EAGLE** [comment]
Thanks!

The error should be fixed with [757f5c2](https://github.com/16EAGLE/basemaps/commit/757f5c2758b4932b705c5d865c8879942544fa4b) and the requested map types were added with [55c7529](https://github.com/16EAGLE/basemaps/commit/55c75295e7daea00a5a411b5ecc457c83ef2089a) (see https://github.com/16EAGLE/basemaps/blob/master/NEWS.md#basemaps-010).
