### ISSUE TITLE
Stubborn white border around maps.

### ISSUE THREAD

**Issue by admahood** [16EAGLE/basemaps#4]
In ggplot, there is a border of blank space when I use basemaps::basemap_gglayer or basemaps::basemap_ggplot. No matter what I do, the map refuses to go all the way to the edge of the plot border. Any way to get rid of this? it basically prevents me from being able to use this package for my visualizations. Other than this, I love the package!

![Rplot](https://user-images.githubusercontent.com/7245247/123475131-308a4980-d5b8-11eb-93d4-c29c4fb88231.png)

**Comment by 16EAGLE** [comment]
Thanks for trying out `basemaps`. Not sure since I don't see your code but I guess this stems from `ggplot`s axis expansion behavior which is the default for any `ggplot`. Here a reproducible example for a basemap without the expansion:

```R
library(ggplot2)
library(basemaps)

data(ext)
set_defaults(map_service = "osm", map_type = "topographic")

gg <- basemap_ggplot(ext)

#default ggplot2 behavior
gg
```
![plot1](https://user-images.githubusercontent.com/23257860/123981355-8ef16680-d9c2-11eb-8ca6-03d40b65e8cb.png)

```R
# with expanion reduced to 0 for both axis
gg + scale_x_continuous(expand = c(0,0)) + scale_y_continuous(expand = c(0,0)) 
```
![plot2](https://user-images.githubusercontent.com/23257860/123981399-93b61a80-d9c2-11eb-96d6-70b646423cd6.png)

Does that solve the issue?

**Comment by 16EAGLE** [comment]
And in case the issue is regarding `ggplot2` plot margins and their removal, here a minimal example of the same map without any white space around it:

```R
gg + scale_x_continuous(expand = c(0,0)) + scale_y_continuous(expand = c(0,0)) + 
  labs(x=NULL, y=NULL) +
  theme(axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        axis.ticks.length = unit(0, "pt"), #length of tick marks
        legend.position = "none",
        panel.background = element_blank(),
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.background = element_blank(), 
        plot.margin = unit(c(0,0,0,0),"mm"))
```
![plot3](https://user-images.githubusercontent.com/23257860/123984382-e1338700-d9c4-11eb-9ffb-e88f248e3391.png)

**Comment by admahood** [comment]
I think that solves it. Thanks!
